<!--
  A plot written by foresight, from docs/public/examples (regenerated by scripts/docs_examples.sh):
  <Plot name="ch1" />              the interactive HTML page, live in the docs: wheel zoom, drag, hotkeys
  <Plot name="cb_logscale" svg />  the static SVG image
  width/height are the plot page size [px] (set terminal ... size W,H), 640x380 by default. A page wider than the
  column is scaled down as a whole (CSS transform): the viewer maps the mouse through it, zoom and pan keep working.
-->
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { withBase } from 'vitepress'

const props = withDefaults(defineProps<{
  name: string
  svg?: boolean
  width?: number
  height?: number
  caption?: string
}>(), { svg: false, width: 640, height: 380, caption: '' })

const src = computed(() => withBase(`/examples/${props.name}.${props.svg ? 'svg' : 'html'}`))
const canvas = ref<HTMLElement | null>(null)
const scale = ref(1)
let observer: ResizeObserver | undefined

onMounted(() => {
  if (!canvas.value || typeof ResizeObserver === 'undefined') return
  observer = new ResizeObserver(([entry]) => {
    scale.value = Math.min(1, entry.contentRect.width / props.width)
  })
  observer.observe(canvas.value)
})
onBeforeUnmount(() => observer?.disconnect())
</script>

<template>
  <figure class="fs-plot" :style="{ maxWidth: `${width + 2}px` }">
    <div ref="canvas" class="fs-plot-canvas" :style="svg ? {} : { height: `${height * scale}px` }">
      <img v-if="svg" :src="src" :alt="caption || name" :width="width" :height="height" loading="lazy" />
      <iframe v-else :src="src" :title="caption || name" :width="width" :height="height" loading="lazy"
              scrolling="no" :style="{ width: `${width}px`, height: `${height}px`, transform: `scale(${scale})` }" />
    </div>
    <figcaption>
      <span v-if="!svg" class="fs-plot-hint">wheel: zoom · drag: pan · right drag: box · <kbd>a</kbd> reset</span>
      <span v-if="caption" class="fs-plot-caption">{{ caption }}</span>
      <a :href="src" target="_blank" rel="noopener">open {{ svg ? 'SVG' : 'page' }} ↗</a>
    </figcaption>
  </figure>
</template>
