#!/usr/bin/env bash
# Embed the interactive viewer src/js/viewer.js into the generated Fortran module
# src/lib/foresight_viewer_js.F90 (one write statement per line: no continuation-line limit).
#
# Usage: scripts/embed_js.sh   (from the repository root; also `fobis rule --ex embed-js`)
set -euo pipefail

src=src/js/viewer.js
out=src/lib/foresight_viewer_js.F90
max=100

# write statements must fit Fortran's 132-column free-form lines
awk -v max="$max" 'length($0) > max {
  printf "%s:%d: line longer than %d characters\n", FILENAME, NR, max > "/dev/stderr"; bad = 1
} END { exit bad }' "$src"
if grep -q $'\t' "$src"; then
  echo "$src: tab characters are not allowed" >&2
  exit 1
fi

{
  cat <<'EOF'
!< foresight_viewer_js, the interactive viewer embedded in HTML pages.
module foresight_viewer_js
!< foresight_viewer_js, the interactive viewer embedded in HTML pages.
!<
!< GENERATED by scripts/embed_js.sh from src/js/viewer.js: do not edit, edit the JavaScript and regenerate.
use penf, only : I4P

implicit none
private
public :: write_viewer_js

contains
   subroutine write_viewer_js(unit)
   !< Write the viewer script, one line per record, on the open formatted `unit`.
   integer(I4P), intent(in) :: unit !< Output unit.

EOF
  sed -e "s/'/''/g" -e "s/^/   write(unit, '(A)') '/" -e "s/\$/'/" "$src"
  cat <<'EOF'
   endsubroutine write_viewer_js
endmodule foresight_viewer_js
EOF
} > "$out"
echo "generated $out from $src"
